[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
lockedin = "EMs5GHLJ1MMGrvVxVQKLjpSXpmkeNfc2gXjvAVEhBr2J"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --experimental-strip-types --test tests/*.test.ts"
